display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: ‹‹
            next: ››
      fields:
        entity__target_id:
          label: Entidad
          separator: ', '
        entity_revision_link:
          label: Revisión
        transition_on:
          separator: ', '
        author:
          separator: ', '
        operations:
          label: Operaciones
  page_1:
    display_title: Página
