add_page_meta: true
output_terms: true
output_fields: true
group: false
lib_helper: false
entity_meta:
  created: created
  langcode: langcode
  name: name
  status: status
  vid: vid
  uid: '0'
  uuid: '0'
enable_ia: true
ia_depth: 3
ia_category_primary: primaryCategory
ia_category_sub: subCategory
vocabs:
  recipe_category: recipe_category
  tags: tags
expose_user_details: ''
expose_user_details_roles:
  authenticated: authenticated
  administrator: administrator
  author: author
  editor: editor
current_user_meta:
  name: '0'
  mail: '0'
  roles: '0'
  created: '0'
  access: '0'
expose_user_details_fields: true
entity_title: entityTitle
entity_type: entityType
entity_bundle: entityBundle
entity_identifier: entityId
group_label: groupLabel
drupal_language: drupalLanguage
drupal_country: drupalCountry
site_name: siteName
key_replacements:
  - ''
_core:
  default_config_hash: N67AkcKPlikWJbwxABv6MSMpGuXe36qWZfH88pEzeqc
