custom_1.settings:
  type: config_object
  label: 'custom_1 Lorem Ipsum settings'
  mapping:
    custom_1:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Custom_1 Lorem ipsum generator page title:'
        source_text:
          type: text
          label: 'Source text for lorem ipsum generation:'
block.settings.custom_1_block:
  type: block_settings
  label: 'Lorem ipsum block'
  mapping:
    loremipsum_block_settings:
      type: text
      label: 'Custom_1 Lorem ipsum block settings'